/*
 * Copyright 2017 George Aristy.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.llorllale.netbeans.youtrack.issues;

import javax.swing.JComponent;
import javax.swing.JPanel;
import org.llorllale.youtrack.api.Issue;
import org.llorllale.youtrack.api.Issues.IssueSpec;

/**
 * 
 *
 * @author George Aristy (george.aristy@gmail.com)
 * @since 0.2.0
 */
public class AsView extends JPanel implements ViewOfIssue {
  private static final long serialVersionUID = -7596322055876803429L;

  private final Issue issue;
  private final FieldsAsTableModel model;

  /** 
   * Creates new form AsView 
   * 
   * @param issue the YouTrack issue to display to the end user
   * @since 0.2.0
   */
  public AsView(Issue issue) {
    this.initComponents();
    this.issue = issue;
    this.model = new FieldsAsTableModel(issue);
    this.fieldsTable.setModel(this.model);
  }

  @Override
  public String issueId() {
    return this.issue.id();
  }

  @Override
  public IssueSpec asSpec() {
    final IssueSpec spec = new IssueSpec(
        this.summaryTxtBox.getText(), 
        this.descriptionTxtBox.getText()
    );
    this.issue.fields().forEach(field -> spec.with(field, field.value()));
    return spec;
  }

  @Override
  public JComponent asView() {
    return this;
  }

  //@checkstyle.OFF Generated Code

  /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    creationDateLbl = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    issueIdTxtBox = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    createdByTxtBox = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    createdOnTxtBox = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    summaryTxtBox = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    descriptionTxtBox = new javax.swing.JTextArea();
    jLabel6 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    fieldsTable = new javax.swing.JTable();

    org.openide.awt.Mnemonics.setLocalizedText(creationDateLbl, org.openide.util.NbBundle.getMessage(AsView.class, "AsView.creationDateLbl.text")); // NOI18N
    creationDateLbl.setName("creationDateLbl"); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AsView.class, "AsView.jLabel1.text")); // NOI18N

    issueIdTxtBox.setEditable(false);
    issueIdTxtBox.setText(org.openide.util.NbBundle.getMessage(AsView.class, "AsView.issueIdTxtBox.text")); // NOI18N
    issueIdTxtBox.setName("issueIdTxtBox"); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AsView.class, "AsView.jLabel2.text")); // NOI18N

    createdByTxtBox.setEditable(false);
    createdByTxtBox.setText(org.openide.util.NbBundle.getMessage(AsView.class, "AsView.createdByTxtBox.text")); // NOI18N
    createdByTxtBox.setName("createdByTxtBox"); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AsView.class, "AsView.jLabel3.text")); // NOI18N

    createdOnTxtBox.setEditable(false);
    createdOnTxtBox.setText(org.openide.util.NbBundle.getMessage(AsView.class, "AsView.createdOnTxtBox.text")); // NOI18N
    createdOnTxtBox.setName("createdOnTxtBox"); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(AsView.class, "AsView.jLabel4.text")); // NOI18N

    summaryTxtBox.setEditable(false);
    summaryTxtBox.setText(org.openide.util.NbBundle.getMessage(AsView.class, "AsView.summaryTxtBox.text")); // NOI18N
    summaryTxtBox.setName("summaryTxtBox"); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(AsView.class, "AsView.jLabel5.text")); // NOI18N

    descriptionTxtBox.setColumns(20);
    descriptionTxtBox.setRows(5);
    descriptionTxtBox.setName("descriptionTxtBox"); // NOI18N
    jScrollPane1.setViewportView(descriptionTxtBox);

    org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(AsView.class, "AsView.jLabel6.text")); // NOI18N

    fieldsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    fieldsTable.setName("fieldsTable"); // NOI18N
    jScrollPane2.setViewportView(fieldsTable);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(105, 105, 105)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(issueIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(createdByTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(createdOnTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(creationDateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel6)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
            .addComponent(jLabel5)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addComponent(summaryTxtBox)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel1)
            .addComponent(issueIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2)
            .addComponent(createdByTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel3)
            .addComponent(createdOnTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(creationDateLbl))
        .addGap(10, 10, 10)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(summaryTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel5)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(jLabel6))
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(273, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField createdByTxtBox;
  private javax.swing.JTextField createdOnTxtBox;
  private javax.swing.JLabel creationDateLbl;
  private javax.swing.JTextArea descriptionTxtBox;
  private javax.swing.JTable fieldsTable;
  private javax.swing.JTextField issueIdTxtBox;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextField summaryTxtBox;
  // End of variables declaration//GEN-END:variables

  //@checkstyle.ON Generated Code
}
