/*
 * Copyright 2017 George Aristy.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.llorllale.netbeans.youtrack.issues;

import javax.swing.JPanel;

/**
 * Configuration dialog for a YouTrack "repository".
 * 
 * <p>We project YouTrack projects as "repositories" as defined by the netbeans platform model.
 * Therefore, the configuration in this view pertains to a single project in YouTrack.
 * 
 * <p>We use these coordinates to triangulate a YouTrack project:
 * 
 * <ul>
 *    <li>The server's rest API url</li>
 *    <li>The project's ID</li>
 *    <li>The user's permanent token (aka "access token" in other systems)</li>
 * </ul>
 *
 * @author George Aristy (george.aristy@gmail.com)
 * @since 0.1.0
 */
public class YtRepoConfigView extends JPanel {
  private static final long serialVersionUID = 6947216488784922827L;
  private final YtRepositoryController controller;

  /**
   * Ctor.
   * 
   * @param controller this view's controller
   * @since 0.1.0
   */
  public YtRepoConfigView(YtRepositoryController controller) {
    this.controller = controller;
    this.initComponents();
  }

  /**
   * The URL string configured by the user for the REST API.
   * 
   * @return the URL string configured by the user for the REST API
   * @since 0.1.0
   */
  public String apiUrl() {
    return this.apiUrlTxtBox.getText();
  }

  /**
   * The project's ID configured by the user.
   * 
   * @return the project's ID configured by the user
   * @since 0.1.0
   */
  public String projectId() {
    return this.projectIdTxtBox.getText();
  }

  /**
   * The user's access token as entered in the dialog.
   * 
   * @return the user's access token as entered in the dialog 
   * @since 0.1.0
   */
  public String permToken() {
    return this.permTokenTxtBox.getText();
  }

    /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    apiUrlTxtBox = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    projectIdTxtBox = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    permTokenTxtBox = new javax.swing.JTextField();
    testBtn = new javax.swing.JButton();
    createBtn = new javax.swing.JButton();

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.jLabel1.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.jLabel2.text")); // NOI18N

    apiUrlTxtBox.setText(org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.apiUrlTxtBox.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.jLabel3.text")); // NOI18N

    projectIdTxtBox.setText(org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.projectIdTxtBox.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.jLabel4.text")); // NOI18N

    permTokenTxtBox.setText(org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.permTokenTxtBox.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(testBtn, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.testBtn.text")); // NOI18N
    testBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        testBtnActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(createBtn, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.createBtn.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel2)
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(apiUrlTxtBox)
                  .addComponent(projectIdTxtBox)
                  .addComponent(permTokenTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)))))
          .addGroup(layout.createSequentialGroup()
            .addGap(48, 48, 48)
            .addComponent(testBtn)
            .addGap(89, 89, 89)
            .addComponent(createBtn)))
        .addContainerGap(65, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(apiUrlTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(projectIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(permTokenTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(40, 40, 40)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(testBtn)
          .addComponent(createBtn))
        .addContainerGap(85, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void testBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBtnActionPerformed
    this.controller.isValid();
  }//GEN-LAST:event_testBtnActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField apiUrlTxtBox;
  private javax.swing.JButton createBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField permTokenTxtBox;
  private javax.swing.JTextField projectIdTxtBox;
  private javax.swing.JButton testBtn;
  // End of variables declaration//GEN-END:variables

}
