/*
 * Copyright 2017 George Aristy.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.llorllale.netbeans.youtrack.issues;

import javax.swing.JPanel;

/**
 * The dialog to configure a YouTrack repository in NetBean's bugtracking framework.
 * 
 * <p>Each repository is mapped to one YouTrack project; hence, only issues from a single project
 * will be managed. Therefore, our "repository coordinates" are:
 * 
 * <ul>
 *    <li>The {@link #apiUrl() REST API URL}</li>
 *    <li>The {@link #userToken() user's permanent token}</li>
 *    <li>The {@link #projectId() project's ID}</li>
 * </ul>
 *
 * @author George Aristy (george.aristy@gmail.com)
 * @since 0.2.0
 */
public class YtRepoConfigView extends JPanel {
  private static final long serialVersionUID = 7591105472682819639L;

  /**
   * Creates new form YtRepoConfigView
   * 
   * @since 0.2.0
   */
  public YtRepoConfigView(YtRepoConfigController controller) {
    this.initComponents();
    this.testBtn.addActionListener(e -> controller.testCoordinates());
    //TODO
//    this.saveBtn.addActionListener(listener);
  }

  /**
   * The URL for YouTrack's REST API, as entered by the user. 
   * Example: http://youtrack/rest.
   * 
   * @return the URL for YouTrack's REST API
   * @since 0.2.0
   */
  public String apiUrl() {
    return this.apiUrlTxtBox.getText();
  }

  /**
   * The project's ID as entered by the user.
   * 
   * @return the project's ID as entered by the user
   * @since 0.2.0
   */
  public String projectId() {
    return this.projectIdTxtBox.getText();
  }

  /**
   * The user's permanent token.
   * 
   * @return the user's permanent token
   * @since 0.2.0
   */
  public String userToken() {
    return this.permTokenTxtBox.getText();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    apiUrlTxtBox = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    permTokenTxtBox = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    projectIdTxtBox = new javax.swing.JTextField();
    testBtn = new javax.swing.JButton();
    saveBtn = new javax.swing.JButton();

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.jLabel1.text")); // NOI18N

    apiUrlTxtBox.setText(org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.apiUrlTxtBox.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.jLabel2.text")); // NOI18N

    permTokenTxtBox.setText(org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.permTokenTxtBox.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.jLabel3.text")); // NOI18N

    projectIdTxtBox.setText(org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.projectIdTxtBox.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(testBtn, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.testBtn.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(saveBtn, org.openide.util.NbBundle.getMessage(YtRepoConfigView.class, "YtRepoConfigView.saveBtn.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(jLabel3)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(apiUrlTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
          .addComponent(projectIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(permTokenTxtBox)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(testBtn)
            .addGap(18, 18, 18)
            .addComponent(saveBtn)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(projectIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(apiUrlTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(permTokenTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(testBtn)
          .addComponent(saveBtn))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField apiUrlTxtBox;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField permTokenTxtBox;
  private javax.swing.JTextField projectIdTxtBox;
  private javax.swing.JButton saveBtn;
  private javax.swing.JButton testBtn;
  // End of variables declaration//GEN-END:variables
}
